### ISSUE TITLE
Where does {{ zoo_id }} gets the value from?

### ISSUE THREAD

**Issue by gvenka008c** [AnsibleShipyard/ansible-zookeeper#24]
@antonlindstrom @mhamrah How does the below work?where does {{ zoo_id }} gets the value from?

- name: Write myid file.
  template: src=myid.j2 dest={{data_dir}}/myid owner=zookeeper group=zookeeper
  tags: deploy

Template myid.j2 has the below
{{ zoo_id }}

**Comment by gvenka008c** [comment]
@kienpham2000 Any update on the above?

**Comment by kienpham2000** [comment]
@gvenka008c it comes from this default config here:
https://github.com/AnsibleShipyard/ansible-zookeeper/blob/master/defaults/main.yml#L12

Which you can overwrite when you include this role at your playbook.

**Comment by gvenka008c** [comment]
I have 3 masters and want to set zoo_id as 1, 2 and 3. I thought {{zoo_id}} is pulled using dynamic inventory. Thanks @kienpham2000

**Comment by kienpham2000** [comment]
@gvenka008c I believe you can set it at your host file like this. Not sure if this is recommend, it's been a while I use ansible :)

master001.example.com zoo_id=1
master002.example.com zoo_id=2

**Comment by gvenka008c** [comment]
@kienpham2000 Thanks. We are using Dynamic Inventory to pull host information. So I need to find a way to get it dynamically. Thanks for the quick response.

**Comment by ernestas-poskus** [comment]
@gvenka008c currently zoo_id is static but this https://github.com/AnsibleShipyard/ansible-zookeeper/pull/29 will solve it

**Comment by ernestas-poskus** [comment]
Fixed by https://github.com/AnsibleShipyard/ansible-zookeeper/pull/29
