### ISSUE TITLE
tarball folder (/opt/src) is hardcoded and thus not configurable

### ISSUE THREAD

**Issue by lhoss** [AnsibleShipyard/ansible-zookeeper#35]
we don't use /opt (instead another special subdir in /usr/local), so we need this to be configurable.

I already fixed this locally and ready to make a PR (after https://github.com/AnsibleShipyard/ansible-zookeeper/pull/34 got merged)

**Comment by ernestas-poskus** [comment]
Why it's not configurable ? In Ansible you can override default variables

**Comment by lhoss** [comment]
but this path (/opt/src) is not yet a role variable, see tarball.yml

**Comment by ernestas-poskus** [comment]
@lhoss yes you are right, then I suggest to extract it into variable leave default as it is and you will be able to change it to satisfy your needs

**Comment by lhoss** [comment]
that's how I've implemented it (will create PR latest tomorrow, after #34 merge), adding new variable:
```
zookeeper_tarball_dir: /opt/src
```

**Comment by ernestas-poskus** [comment]
@lhoss again thank you for contribution, your PR's merged

**Comment by lhoss** [comment]
happy to contribute !
keeping up the improvements, just created https://github.com/AnsibleShipyard/ansible-zookeeper/pull/38

**Comment by lhoss** [comment]
you can close
https://github.com/AnsibleShipyard/ansible-zookeeper/pull/38 fixed this

**Comment by ernestas-poskus** [comment]
issue resolved
