### ISSUE TITLE
[New Feature] configurable autopurge for zookeeper snapshots and logs

### ISSUE THREAD

**Issue by lhoss** [AnsibleShipyard/ansible-zookeeper#36]
A very useful zookeeper feature, to avoid filling up too much your zookeeper data+log dirs:
A reasonable config to add in zoo.cfg would be for ex:

```
+autopurge.purgeInterval=24
+autopurge.snapRetainCount=10
```

I propose to make this configurable, introducing 2 new role variables (that keep the current default, to not use autopurge):
```
zookeeper_autopurge_purgeInterval=0
zookeeper_autopurge_snapRetainCount=10
```

Again, I'm ready to contribute this. Before creating the PR, happy for comments?
@ernestas-poskus ?

**Comment by ernestas-poskus** [comment]
as long as default is not auto purge :+1:
