### ISSUE TITLE
Zookeeper not starting

### ISSUE THREAD

**Issue by sonali2197** [AnsibleShipyard/ansible-zookeeper#6]
Hi,

I'm running the playbook.rml for ansible-mesos-playbook which installs ansible-zookeeper as one of the roles. It runs through the Redhat.yml file creating data folders, log folders, setting the upstart script etc. When it comes to running/starting the zookeeper service it errors out as below. Any idea why this is?

TASK: [ansible-zookeeper | Update apt cache] ********************************** 
skipping: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Apt install required system packages.] ************* 
skipping: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Overwrite myid file.] ****************************** 
skipping: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Overwrite default config file] ********************* 
skipping: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Restart zookeeper] ********************************* 
skipping: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | file path=/opt/src state=directory] **************** 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | file path={{zookeeper_dir}} state=directory] ******* 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Download zookeeper version.] *********************** 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Install OS Packages] ******************************* 
ok: [svdpdac015.techlabs.accenture.com] => (item=libselinux-python)

TASK: [ansible-zookeeper | Unpack tarball.] *********************************** 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | group name=zookeeper system=yes] ******************* 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | user name=zookeeper group=zookeeper system=yes] **** 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Change ownership on zookeeper directory.] ********** 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Create zookeeper data folder.] ********************* 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Create zookeeper logs folder.] ********************* 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Upstart script.] *********************************** 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Write myid file.] ********************************** 
ok: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Configure zookeeper] ******************************* 
changed: [svdpdac015.techlabs.accenture.com]

TASK: [ansible-zookeeper | Start zookeeper] *********************************** 
failed: [svdpdac015.techlabs.accenture.com] => {"failed": true}
msg: zookeeper: unrecognized service
zookeeper: unrecognized service

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/playbook.retry

svdpdac015.techlabs.accenture.com : ok=21   changed=1    unreachable=0    failed=1   
svdpdac016.techlabs.accenture.com : ok=6    changed=0    unreachable=0    failed=0   
svdpdac017.techlabs.accenture.com : ok=6    changed=0    unreachable=0    failed=0

**Comment by JasonGiedymin** [comment]
I'm actually in the middle of adding test scripts for this playbook. You should see the commit reference here tonight. So it will get some testing in some manner. Next after this is the Mesos playbook. I know there are issues there but since this playbook is a dependency I had address this repo first.

-Jason

**Comment by sonali2197** [comment]
Hi! Any updates on this? Is the issue specific to Redhat?

**Comment by JasonGiedymin** [comment]
I'm about a day behind, tonight is when I have time.

-Jason

**Comment by JasonGiedymin** [comment]
I've managed to update the CI of this repo, as you can see under [travis it does pass](https://travis-ci.org/AnsibleShipyard/ansible-zookeeper/builds/53514533). A accompanied dockerfile is also now [available](https://registry.hub.docker.com/u/ansibleshipyard/ansible-zookeeper/).

Knowing this can you supply some more information on your situation? I'l see if I can help.

**Comment by JasonGiedymin** [comment]
No reply. Closing this issue.
