### ISSUE TITLE
systemd - ZK starting up before the network is ready and available after a server reboot

### ISSUE THREAD

**Issue by Darwiner** [AnsibleShipyard/ansible-zookeeper#70]
In `ansible-zookeeper/templates/zookeeper.service.j2`

It might be a good idea to change the following:

```
[Unit]
Description=ZooKeeper
```

To:

```
[Unit]
Description=ZooKeeper
After=network.target
Wants=network.target
```

Everything works fine with a server that is already up and running, but in the case of rebooting a server, ZK starts too early, before the network is even available, leading to errors about not being able to resolve other cluster member hostnames, or timing out while trying to reach them.

**Comment by lhoss** [comment]
@Darwiner you made a valid point, why did you close the issue (without any referenced PR) ?
