### ISSUE TITLE
zookeeper version 3.4.9 is unavailable

### ISSUE THREAD

**Issue by gavin-meyers** [AnsibleShipyard/ansible-zookeeper#73]
Need to update the zookeeper version to something other than 3.4.9. This version is unavailable. and the role fails when we run the playbook.

Please update to the latest (3.4.11) or provide a way to override the version.

Created a pull req: https://github.com/AnsibleShipyard/ansible-zookeeper/pull/74

**Comment by Light-Gao** [comment]
The default configuration of zookeeper version is in `defaults/main.yml`. U may change it as needed permanently in `defaults/main.yml` or just give playbook a temporary value for zookeeper version with `-e zookeeper_version=3.4.11` when you run `ansible-playbook`.

**Comment by ernestas-poskus** [comment]
Updated in https://github.com/AnsibleShipyard/ansible-zookeeper/pull/78
